name: "setup"
description: "setup for python environment"
inputs:
  python-version:
    description: "The python version to use"
    required: true
    default: "3.8"
  project-dir:
    description: "The project directory"
    required: true
    default: "."
runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"
    - name: "Install dependencies"
      run: |
        cd ${{ inputs.project-dir }}
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
