name: "Test quote display"
description: "This action does testing for quote display"
inputs:
  project-dir:
    description: "The project directory"
    required: true
    default: "."
runs:
  using: "composite"
  steps:
    - name: "Run tests"
      run: cd ${{ inputs.project-dir }} && pytest
      shell: bash
