name: backend-ci
run-name: backend-ci
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test_quote_display:
    name: test quote_disp
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: ./.github/setup
      - uses: ./quote_disp/action
  test_quote_gen:
    name: test quote_gen
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: ./.github/setup
      - uses: ./quote_gen/action
