name: backend-ci
run-name: backend-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  test_quote_display:
    name: test quote_disp
    runs-on: ubuntu-latest
    steps:
      - uses: ./setup/setup.yml
      - uses: ../quote_disp/action/ci.yml
  test_quote_gen:
    name: test quote_gen
    runs-on: ubuntu-latest
    steps:
      - uses: ./setup/setup.yml
      - uses: ../quote_gen/action/ci.yml
