name: quote_disp-ci
run-name: quote_disp-ci
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test_quote_display:
    name: test quote_disp
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: ./.github/setup
        with:
          project-dir: "./quote_disp"
      - uses: ./quote_disp/action
        with:
          project-dir: "./quote_disp"
