name: "setup"
description: "setup for python environment"
inputs:
  python-version:
    description: "The python version to use"
    required: true
    default: "3.8"
runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"
    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
